### ISSUE TITLE
Gui sender tomme patch-operasjoner

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/concept-catalogue-gui#152]
Det ser ut til at når bruker legger inn ny verdi i et felt, sender gui patch-operasjoner på mange flere felt enn det som er endret.
Forventning er at kun feltet som er oppdatert, blir sendt i patchen.
I eksempelet er det kun feltet "Merknad" som er endret.
![image](https://user-images.githubusercontent.com/1702357/67291484-e34ffd80-f4e1-11e9-8880-1d5521084c9f.png)

**Comment by lillelars** [comment]
Tested ok in ut1
