### ISSUE TITLE
Implementere søk etter begrep

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/concept-catalogue-gui#249]
Hentet fra behov: https://github.com/Informasjonsforvaltning/behov/issues/75

Som: Intern leser og skrivebruker
Gitt at jeg står i Registreringsløsningens landingsside kataloger
Og jeg klikker på Begrepskatalog_
Ønsker jeg å: kunne søke blant begrepene i min liste (søket skal gå mot feltene "anbefalt term", "tillatt term" og "frarådt term")
Slik at: jeg enkelt kan se begreper som allerede er registrert i begrepskatalogen

Relatert til epos: #329

Lenke til trådskisser: https://vfy2gg.axshare.com/#g=1&p=oversiktside_begrep_skriverolle
Lenke til trådskisser for lesebruker: https://vfy2gg.axshare.com/#g=1&p=oversiktside_begrep_leserolle
Lenke til design (består av flere skisser som viser hele flyten): https://invis.io/3SRCN149CQN#/385601277_BEGREP-REG-Relaterte-Default--D-
Lenke til løsningsarkitektur: denne løses ved at api-et må støtte query på list begreper samt at gui må implementere "standard" søk.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Akseptansekriterier:
,# language: no
Egenskap:
Kriterier:
⦁ Søk på begrep - skrivetilgang
⦁ Søk på begrep - lesetilgang

Dekkes ikke: (Dekkes i andre brukerhistorier)

Referanser:
Scenario: Søk på begrep - skrivetilgang
Gitt at bruker er pålogget med skrivetilgang
og bruker har startet opp siden "Begrep fra..."
Når bruker registerer søkeordet "Saksarkiv" og klikker på søkeikonet
Så skal listen med begrep inneholde anbefalt term = saksakiv"

Scenario: Søk på begrep - lesetilgang
Gitt at bruker er pålogget med lesetilgang
og bruker har startet opp siden "Begrep fra..."
Når bruker registerer søkeordet "Saksarkiv" og klikker på søkeikonet
Så skal listen med begrep inneholde anbefalt term = saksakiv"

**Comment by lillelars** [comment]
@joebrreg kan denne lukkes?
nytt søk er forbedret - resultater er innsnevret :)

**Comment by shenluna** [comment]
Implementert søk på anbefalt term
