### ISSUE TITLE
Sortering på fagområde gir bruker "Something went wrong"

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/concept-catalogue-gui#252]
Testet i demo, i chrome.
Finn igjen feilen: 
- Velg begrepskatalogen i registreringsløsningen
-  forsøk å sorter på fagområde

Resultat:

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/56137055-cf7b-43d8-b904-41154b9b691e)

**Comment by jeffreiffers** [comment]
Klar til test i staging.
https://registrering-begrep.staging.fellesdatakatalog.digdir.no/910244132
