### ISSUE TITLE
Refresh SSO token in chrome returns 400 in development 

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/concept-catalogue-gui#253]
After succesfull login the app tries to refresh the token. In chrome this results to invalid request.

`Request URL: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/token
Request Method: POST
Status Code: 400 
Remote Address: 34.102.250.50:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-origin: http://localhost:8203
access-control-expose-headers: Access-Control-Allow-Methods
alt-svc: clear
cache-control: no-store
content-length: 69
content-type: application/json
date: Tue, 19 Jan 2021 11:16:07 GMT
pragma: no-cache
via: 1.1 google`

`{
textPayload: "[0m[33m10:51:18,048 WARN  [org.keycloak.events] (default task-196) type=REFRESH_TOKEN_ERROR, realmId=fdk, clientId=concept-catalogue-gui, userId=null, ipAddress=46.212.73.41, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
"
insertId: "te1j8emkb6l2nmzvj"
resource: {
type: "k8s_container"
labels: {
namespace_name: "staging"
container_name: "sso"
project_id: "digdir-fdk-dev"
cluster_name: "digdir-fdk-dev"
location: "europe-north1-a"
pod_name: "sso-dd6d45855-xs826"
}
}
timestamp: "2021-01-19T10:51:18.049654510Z"
severity: "INFO"
labels: {
k8s-pod/pod-template-hash: "dd6d45855"
k8s-pod/fdk_service: "sso"
}
logName: "projects/digdir-fdk-dev/logs/stdout"
receiveTimestamp: "2021-01-19T10:51:20.258287883Z"`

**Comment by jeffreiffers** [comment]
Dette er lokal feil pga refresh token og localhost. Dette kan løses på følgende måte: https://szoradi-balazs.medium.com/keycloak-samesite-cookie-attribute-e45cb2801180

**Comment by matsjs** [comment]
Samesite flagget som er refert til i posten over finnes ikke lenger. Kan nå løses ved å sette `checkLoginIframe: false` i `src/lib/auth/auth.ts` -> `keycloakInitOptions`.
