### ISSUE TITLE
Begreps-registrering - Validering av URL

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/concept-catalogue-gui#255]
Det skal ikke være lov å oppdatere et begrep med en ugyldig URL på de inputfelter man kan sette inn lenker.
Gjelder:
"Lenke til kilde"
"Lenke til Omfang"
Portal klarer dermed heller ikke å oppdatere begrepet.

Steg for å gjenskape:

1) Bytt en godkjent URL til noe som ikke er gyldig URL
2) gå ut av begrepet og inn igjen. Da ser du at det fortsatt står en ugyldig lenke der
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/4227e2b8-1fb4-4901-91a7-1f4866ec5abb)

**Comment by lillelars** [comment]
@joebrreg @Te-Bert Dette må vi avklare hvordan vi ønsker at skal fungere før vi tar denne videre.

**Comment by matsjs** [comment]
@lillelars @joebrreg @Te-Bert Kom dere noen vei på denne?
Vi kan ganske enkelt sørge for at kun gyldige begrep/ verdier blir sendt til back-end, men da vil man ikke kunne lagre "utkast" med ugyldige verdier.

En relatert tanke her er å droppe all validering på front-end og kun støtte seg på back-end validering. Da bør vi finne et format på feilmeldinger fra back-end som lar oss sette røde bokser på felt der feil inntreffer i front-end. Oppsiden er at vi bare får en "validator" å vedlikeholde, men muligens en medium/stor jobb for relativt lite payoff. Tanker @stigbd ?

**Comment by stigbd** [comment]
> @lillelars @joebrreg @Te-Bert Kom dere noen vei på denne?
> Vi kan ganske enkelt sørge for at kun gyldige begrep/ verdier blir sendt til back-end, men da vil man ikke kunne lagre "utkast" med ugyldige verdier.
> 
> En relatert tanke her er å droppe all validering på front-end og kun støtte seg på back-end validering. Da bør vi finne et format på feilmeldinger fra back-end som lar oss sette røde bokser på felt der feil inntreffer i front-end. Oppsiden er at vi bare får en "validator" å vedlikeholde, men muligens en medium/stor jobb for relativt lite payoff. Tanker @stigbd ?

Vi går i disse dager igjennom arbeidsflyten i dette skjermbildet, og det vil kome endringar. Dette issuet vil bli løyst som ein del av dette arbeidet.

**Comment by shenluna** [comment]
Lukker denne da dette vil bli løst med ny begrepsflyt #399
