### ISSUE TITLE
Problemer med import av begreper fra regneark 

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/concept-catalogue-gui#278]
SSB har forsøkt å importere begreper fra regneark. De har prøvd å følge https://github.com/Informasjonsforvaltning/concept-catalogue-gui/issues.

De får 400 feil.
![image](https://user-images.githubusercontent.com/17720749/122878468-16dacf00-d338-11eb-9f2b-6c8a3aa5ef20.png)

Se regnark med begreper: https://teams.microsoft.com/l/file/8718E38D-1671-4686-B3E4-21202428E8C6?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=csv&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1%2FDelte%20dokumenter%2FModellkatalog%2FSSB_IM_Begreper_uten_gule_K.csv&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1&serviceName=teams&threadId=19:1d63088cc0e1451cb991a9ccd9d8ada6@thread.skype&groupId=937040ec-fca4-412c-97ff-28d0f60c75a3

**Comment by ToHelland** [comment]
Jenny har nå forsøkt å importere linje for linje. Dette går ok, men feiler på et av begrepene:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/THE/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/THE/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/THE/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=NO-BOK style='tab-interval:35.4pt;word-wrap:break-word'>




Classification Family | klassifikasjonsfamilie
-- | --




<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri;color:white;mso-color-alt:windowtext;
mso-fareast-language:EN-US'>osv</span><span style='mso-ascii-font-family:Calibri;
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;mso-fareast-language:
EN-US'><o:p></o:p></span></p>


</body>

</html>

**Comment by stigbd** [comment]
Teksten i kommentaren er uleseleg for meg, dessverre.

**Comment by ToHelland** [comment]
Kopierte inn på nytt.

**Comment by ToHelland** [comment]
Jenny i SSB stilte spørsmål om feilen kunne henge sammen med at hun hadde fjernet alle nn kolonner fra concept_sample mal, siden dette ikke er noe hun skulle bruke? Hun forsøkte å legge inn igjen kolonnene uten innhold, men får fortsatt status code 400.

**Comment by shenluna** [comment]
@ToHelland Hei Tore, det har vært en feil på importen som ble rettet i på mandag, kan du be henne Jenny i SSB prøve på nytt?

**Comment by ToHelland** [comment]
@shenluna I følge SSB funker det nå:-)
