### ISSUE TITLE
Bedre feilmeldinger ved import

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/concept-catalogue-gui#282]
Atm vil alle feil ved import være en generell 400, bør ha med en kort setning om hva som faktisk feilet.

![122878468-16dacf00-d338-11eb-9f2b-6c8a3aa5ef20](https://user-images.githubusercontent.com/50194012/123626758-78f07400-d811-11eb-8320-ee9b92e666d9.png)

- [x] Legg til feilmelding i response-body fra backend
- [x] Vis feilmelding i frontend

**Comment by shenluna** [comment]
Testet med en fil som har feil dato på et av begrepene og får følgende feilmedling
![image](https://user-images.githubusercontent.com/73637969/128701836-3d6d110e-ce1a-4053-a5cd-f9f3e07e1323.png)
Er det muligheter for å få noe mer detaljert feilmelding på hva som feiler?

**Comment by NilsOveTen** [comment]
> Testet med en fil som har feil dato på et av begrepene og får følgende feilmedling
> Er det muligheter for å få noe mer detaljert feilmelding på hva som feiler?

Er vel det @matsjs har lagt til? Du testet i staging? Det ser ut til at disse endringene har blitt overskrevet der av en pr fra dependabot.

**Comment by shenluna** [comment]
Ah takk for tips @NilsOveTen, tenkte ikke på å sjekke om det var det siste som lå ute. Jeg satte den til å rulle ut på nytt så skal jeg få testet igjen :)

**Comment by shenluna** [comment]
Testet Ok,
Brukeren får nå mye mer detaljerte feilmeldinger, eksempelvis:
![image](https://user-images.githubusercontent.com/73637969/130028136-4abcc3a5-3d99-47e9-8f33-84d4ea505bf9.png)
