### ISSUE TITLE
URL som blir rapportert ugyldige: for streng validering?

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/concept-catalogue-gui#350]
> Det ser ut til at dere har lagt inn litt for streng validering av URL’er, slik at den ikke godtar URL’er fra Lovdata. Er dette noe dere kjenner til, og er det i så fall noe dere har planer om å gjøre noe med? 

Eksempel på url får feilmelding:
`https://lovdata.no/dokument/NL/lov/1992-07-17-100/`

Dette er både et problem i manuell inntasting og import av begreper.

Andre eksempler på URL'er mot Lovdata som ikke går igjennom:
![invalid_ur](https://user-images.githubusercontent.com/1702357/156002307-d0a34eaf-1c90-4147-bd29-0a6961c63393.png)

**Comment by oyvindis** [comment]
@stigbd Kan du gjøre en ny test og se om saken kan lukkes?
